import NavbarComponent from "./components/NavbarComponent";
import "./styles/index.scss";

export const metadata = {
  title: "Grégory Hue | Portfolio",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavbarComponent/>
        <div className="frame">
          <div className="container">{children}</div>
        </div>
        <div id="stars" />
        <div id="stars2" />
        <div id="stars3" />
      </body>
    </html>
  );
}
